### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by zbeekman** [fluidkeys/fluidkeys#199]
It might be nice to add a CONTRIBUTING.md file to help point people in the right direction for opening pull requests and development practices.

**Comment by paulfurley** [comment]
For now we don't have much to say regarding development practices: we have our own ideas, but until we receive any contributions that *don't* fit our practices, I wouldn't know what to write in it!

I'm also keen not to burden new contributors with things to read until not doing so becomes an issue for us.

I'm going to close this issue for now, but if you think i've missed a wider point then please re-open it @zbeekman
