### ISSUE TITLE
Panic on Arch Linux with crontab emulation

### ISSUE THREAD

**Issue by deraffe** [fluidkeys/fluidkeys#274]
- Fluidkeys 0.3.1 (from git 0.3.1.r0.g7f56a48)
- Arch Linux
- gpg (GnuPG) 2.2.12

While hacking away at the `PKGBUILD` (#184), I finally tried *using* fluidkeys, and it turns out it wants to do strange things with my crontab.
I on Arch Linux and use [`systemd-cron-next`](https://github.com/systemd-cron/systemd-cron-next), a compatibility layer for systemd timers. When trying `fk setup` I got the following traceback:

```
panic: exit status 1

goroutine 1 [running]:
log.Panic(0xc0000c7ec0, 0x1, 0x1)
        /usr/lib/go/src/log/log.go:326 +0xc2
main.ensureCrontabStateMatchesConfig()
        fluidkeys/main.go:103 +0xb9
main.main()
        fluidkeys/main.go:87 +0x1fa
```

Which I traced back to the scheduler trying to do a `crontab -r`, which fails on my system with

```
failed to remove /var/spool/cron/deraffe: Permission denied (os error 13)
```

Is the handling of crontab going to be changed (like not trying to write to it without asking me) or should I raise this issue with `systemd-cron-next` instead?

I haven't had time yet to test what happens with `systemd-cron-next` uninstalled.

**Comment by paulfurley** [comment]
Thanks for trying Fluidkeys @deraffe and for the detailed bug report.

Sorry for the aggressive crontab behaviour, I think you're right that we should ask first.  This is high up my list of dev tasks.

> Is the handling of crontab going to be changed (like not trying to write to it without asking me) or should I raise this issue with systemd-cron-next instead?

Yes it will change, and I *think* we can get away without using `crontab -r` at all. That said, it seems `crontab -r` is a useful thing for a compatibility layer to implement, so perhaps you should raise it with systemd-cron-next anyway?

In the meantime you should be able to prevent fluidkeys from touching crontab at all by adding this line:
```
run_from_cron = true
```

to `~/.config/fluidkeys/config.toml`

Let me know if that gets you up and running :)

**Comment by deraffe** [comment]
It's

```
run_from_cron = false
```
but it worked.

**Comment by paulfurley** [comment]
@deraffe I *think* https://github.com/fluidkeys/fluidkeys/pull/283 should close this since we no longer use `crontab -r`. 

I'm keeping another [ticket open on our Trello](https://trello.com/c/IPAkjU1s) about how/whether to explicitly ask before modifying a user's crontab.

If #283 hasn't fixed your issue then by all means re-open this issue. Thanks!
