### ISSUE TITLE
Dep is a dependency.

### ISSUE THREAD

**Issue by MatthewCroughan** [fluidkeys/fluidkeys#31]
Might be worth noting that me, a few friends, didn't have `dep` installed, so therefore needed to get it. A bit funny 🐔🥚

**Comment by paulfurley** [comment]
Thanks for the feedback, good point. A bit later today can you try installing via `apt` instead? We haven't quite released `0.1.0` yet so you're ahead of the game ;)

**Comment by paulfurley** [comment]
@MatthewCroughan We've released `0.1.0`, if you'd like to give it a shot, see the debian/ubuntu install instructions :)

https://github.com/fluidkeys/fluidkeys#install-on-debian--ubuntu
