### ISSUE TITLE
Mnemonic-Password relationship not clear to user.

### ISSUE THREAD

**Issue by MatthewCroughan** [fluidkeys/fluidkeys#38]
When generating a key it is not clear that the mnemonic phrase given is not directly derivative of the private key itself. This is the convention with most crypto-currencies. It should be made clear that the mnemonic phrase is a password for the key that is currently being generated, and that two separate things are being created, your mnemonic phrase (just password for your private key) and the private key itself.

**Comment by idrysdale** [comment]
@MatthewCroughan good point! We'll have a go at making this more explicit

**Comment by paulfurley** [comment]
I *think* we're clearer on this now. Thanks for raising!
