### ISSUE TITLE
NOTE: We record bugs in our public Trello board

### ISSUE THREAD

**Issue by paulfurley** [fluidkeys/fluidkeys#88]
[https://trello.com/b/dB9j4JaG/fluidkeys?menu=filter&filter=label:BUG](https://trello.com/b/dB9j4JaG/fluidkeys?menu=filter&filter=label:BUG)

**Comment by zbeekman** [comment]
Question: Do you just migrate them from GH over there? Or are users supposed to submit them over there? (I'm new to Trello)

It seems that this information might be better placed in a README.md or CONTRIBUTING.md

**Comment by paulfurley** [comment]
Superceded by #201 and #202
